version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.11-management
    ports:
      - "5672:5672"
      - "15672:15672"
    command: rabbitmq-server
    tty: true
    stdin_open: true
    restart: unless-stopped
